from __future__ import annotations

from typing import Any, Dict, List

COUNTRIES: List[Dict[str, Any]] = [
    {
        "country": "United States",
        "iso3": "USA",
        "region": "North America",
        "lat": 39.8283,
        "lon": -98.5795,
        "timezone": "America/New_York",
        "locations": [
            ("New York", 40.7128, -74.0060, "America/New_York"),
            ("Chicago", 41.8781, -87.6298, "America/Chicago"),
            ("Los Angeles", 34.0522, -118.2437, "America/Los_Angeles"),
        ],
        "index": {"name": "S&P 500", "symbol": "^GSPC"},
    },
    {
        "country": "Canada",
        "iso3": "CAN",
        "region": "North America",
        "lat": 56.1304,
        "lon": -106.3468,
        "timezone": "America/Toronto",
        "locations": [
            ("Toronto", 43.6532, -79.3832, "America/Toronto"),
            ("Vancouver", 49.2827, -123.1207, "America/Vancouver"),
            ("Calgary", 51.0447, -114.0719, "America/Edmonton"),
        ],
        "index": {"name": "S&P/TSX Composite", "symbol": "^GSPTSE"},
    },
    {
        "country": "Mexico",
        "iso3": "MEX",
        "region": "North America",
        "lat": 23.6345,
        "lon": -102.5528,
        "timezone": "America/Mexico_City",
        "locations": [("Mexico City", 19.4326, -99.1332, "America/Mexico_City")],
        "index": {"name": "S&P/BMV IPC", "symbol": "^MXX"},
    },
    {
        "country": "Brazil",
        "iso3": "BRA",
        "region": "South America",
        "lat": -14.2350,
        "lon": -51.9253,
        "timezone": "America/Sao_Paulo",
        "locations": [
            ("Sao Paulo", -23.5558, -46.6396, "America/Sao_Paulo"),
            ("Brasilia", -15.7939, -47.8828, "America/Sao_Paulo"),
            ("Manaus", -3.1190, -60.0217, "America/Manaus"),
        ],
        "index": {"name": "Bovespa", "symbol": "^BVSP"},
    },
    {
        "country": "Argentina",
        "iso3": "ARG",
        "region": "South America",
        "lat": -38.4161,
        "lon": -63.6167,
        "timezone": "America/Argentina/Buenos_Aires",
        "locations": [
            ("Buenos Aires", -34.6037, -58.3816, "America/Argentina/Buenos_Aires")
        ],
        "index": {"name": "MERVAL", "symbol": "^MERV"},
    },
    {
        "country": "Chile",
        "iso3": "CHL",
        "region": "South America",
        "lat": -35.6751,
        "lon": -71.5430,
        "timezone": "America/Santiago",
        "locations": [("Santiago", -33.4489, -70.6693, "America/Santiago")],
        "index": {"name": "S&P IPSA", "symbol": "^IPSA"},
    },
    {
        "country": "United Kingdom",
        "iso3": "GBR",
        "region": "Europe",
        "lat": 55.3781,
        "lon": -3.4360,
        "timezone": "Europe/London",
        "locations": [("London", 51.5072, -0.1276, "Europe/London")],
        "index": {"name": "FTSE 100", "symbol": "^FTSE"},
    },
    {
        "country": "Germany",
        "iso3": "DEU",
        "region": "Europe",
        "lat": 51.1657,
        "lon": 10.4515,
        "timezone": "Europe/Berlin",
        "locations": [("Berlin", 52.5200, 13.4050, "Europe/Berlin")],
        "index": {"name": "DAX", "symbol": "^GDAXI"},
    },
    {
        "country": "France",
        "iso3": "FRA",
        "region": "Europe",
        "lat": 46.2276,
        "lon": 2.2137,
        "timezone": "Europe/Paris",
        "locations": [("Paris", 48.8566, 2.3522, "Europe/Paris")],
        "index": {"name": "CAC 40", "symbol": "^FCHI"},
    },
    {
        "country": "Spain",
        "iso3": "ESP",
        "region": "Europe",
        "lat": 40.4637,
        "lon": -3.7492,
        "timezone": "Europe/Madrid",
        "locations": [("Madrid", 40.4168, -3.7038, "Europe/Madrid")],
        "index": {"name": "IBEX 35", "symbol": "^IBEX"},
    },
    {
        "country": "Italy",
        "iso3": "ITA",
        "region": "Europe",
        "lat": 41.8719,
        "lon": 12.5674,
        "timezone": "Europe/Rome",
        "locations": [("Rome", 41.9028, 12.4964, "Europe/Rome")],
        "index": {"name": "FTSE MIB", "symbol": "FTSEMIB.MI"},
    },
    {
        "country": "Netherlands",
        "iso3": "NLD",
        "region": "Europe",
        "lat": 52.1326,
        "lon": 5.2913,
        "timezone": "Europe/Amsterdam",
        "locations": [("Amsterdam", 52.3676, 4.9041, "Europe/Amsterdam")],
        "index": {"name": "AEX", "symbol": "^AEX"},
    },
    {
        "country": "Switzerland",
        "iso3": "CHE",
        "region": "Europe",
        "lat": 46.8182,
        "lon": 8.2275,
        "timezone": "Europe/Zurich",
        "locations": [("Zurich", 47.3769, 8.5417, "Europe/Zurich")],
        "index": {"name": "Swiss Market Index", "symbol": "^SSMI"},
    },
    {
        "country": "Sweden",
        "iso3": "SWE",
        "region": "Europe",
        "lat": 60.1282,
        "lon": 18.6435,
        "timezone": "Europe/Stockholm",
        "locations": [("Stockholm", 59.3293, 18.0686, "Europe/Stockholm")],
        "index": {"name": "OMX Stockholm 30", "symbol": "^OMX"},
    },
    {
        "country": "Norway",
        "iso3": "NOR",
        "region": "Europe",
        "lat": 60.4720,
        "lon": 8.4689,
        "timezone": "Europe/Oslo",
        "locations": [("Oslo", 59.9139, 10.7522, "Europe/Oslo")],
        "index": {"name": "Oslo Bors Benchmark", "symbol": "OSEBX.OL"},
    },
    {
        "country": "Poland",
        "iso3": "POL",
        "region": "Europe",
        "lat": 51.9194,
        "lon": 19.1451,
        "timezone": "Europe/Warsaw",
        "locations": [("Warsaw", 52.2297, 21.0122, "Europe/Warsaw")],
        "index": {"name": "WIG20", "symbol": "^WIG20"},
    },
    {
        "country": "Turkey",
        "iso3": "TUR",
        "region": "Europe / Asia",
        "lat": 38.9637,
        "lon": 35.2433,
        "timezone": "Europe/Istanbul",
        "locations": [("Istanbul", 41.0082, 28.9784, "Europe/Istanbul")],
        "index": {"name": "BIST 100", "symbol": "XU100.IS"},
    },
    {
        "country": "Russia",
        "iso3": "RUS",
        "region": "Europe / Asia",
        "lat": 61.5240,
        "lon": 105.3188,
        "timezone": "Europe/Moscow",
        "locations": [
            ("Moscow", 55.7558, 37.6173, "Europe/Moscow"),
            ("Yekaterinburg", 56.8389, 60.6057, "Asia/Yekaterinburg"),
            ("Vladivostok", 43.1155, 131.8855, "Asia/Vladivostok"),
        ],
        "index": {"name": "MOEX Russia", "symbol": "IMOEX.ME"},
    },
    {
        "country": "China",
        "iso3": "CHN",
        "region": "Asia",
        "lat": 35.8617,
        "lon": 104.1954,
        "timezone": "Asia/Shanghai",
        "locations": [
            ("Beijing", 39.9042, 116.4074, "Asia/Shanghai"),
            ("Shanghai", 31.2304, 121.4737, "Asia/Shanghai"),
            ("Chengdu", 30.5728, 104.0668, "Asia/Shanghai"),
        ],
        "index": {"name": "SSE Composite", "symbol": "000001.SS"},
    },
    {
        "country": "Hong Kong",
        "iso3": "HKG",
        "region": "Asia",
        "lat": 22.3193,
        "lon": 114.1694,
        "timezone": "Asia/Hong_Kong",
        "locations": [("Hong Kong", 22.3193, 114.1694, "Asia/Hong_Kong")],
        "index": {"name": "Hang Seng", "symbol": "^HSI"},
    },
    {
        "country": "Japan",
        "iso3": "JPN",
        "region": "Asia",
        "lat": 36.2048,
        "lon": 138.2529,
        "timezone": "Asia/Tokyo",
        "locations": [("Tokyo", 35.6762, 139.6503, "Asia/Tokyo")],
        "index": {"name": "Nikkei 225", "symbol": "^N225"},
    },
    {
        "country": "South Korea",
        "iso3": "KOR",
        "region": "Asia",
        "lat": 35.9078,
        "lon": 127.7669,
        "timezone": "Asia/Seoul",
        "locations": [("Seoul", 37.5665, 126.9780, "Asia/Seoul")],
        "index": {"name": "KOSPI", "symbol": "^KS11"},
    },
    {
        "country": "India",
        "iso3": "IND",
        "region": "Asia",
        "lat": 20.5937,
        "lon": 78.9629,
        "timezone": "Asia/Kolkata",
        "locations": [
            ("Mumbai", 19.0760, 72.8777, "Asia/Kolkata"),
            ("Delhi", 28.6139, 77.2090, "Asia/Kolkata"),
            ("Bengaluru", 12.9716, 77.5946, "Asia/Kolkata"),
        ],
        "index": {"name": "NIFTY 50", "symbol": "^NSEI"},
    },
    {
        "country": "Singapore",
        "iso3": "SGP",
        "region": "Asia",
        "lat": 1.3521,
        "lon": 103.8198,
        "timezone": "Asia/Singapore",
        "locations": [("Singapore", 1.3521, 103.8198, "Asia/Singapore")],
        "index": {"name": "Straits Times", "symbol": "^STI"},
    },
    {
        "country": "Thailand",
        "iso3": "THA",
        "region": "Asia",
        "lat": 15.8700,
        "lon": 100.9925,
        "timezone": "Asia/Bangkok",
        "locations": [("Bangkok", 13.7563, 100.5018, "Asia/Bangkok")],
        "index": {"name": "SET Index", "symbol": "^SET.BK"},
    },
    {
        "country": "Indonesia",
        "iso3": "IDN",
        "region": "Asia",
        "lat": -0.7893,
        "lon": 113.9213,
        "timezone": "Asia/Jakarta",
        "locations": [
            ("Jakarta", -6.2088, 106.8456, "Asia/Jakarta"),
            ("Surabaya", -7.2575, 112.7521, "Asia/Jakarta"),
            ("Makassar", -5.1477, 119.4327, "Asia/Makassar"),
        ],
        "index": {"name": "Jakarta Composite", "symbol": "^JKSE"},
    },
    {
        "country": "Malaysia",
        "iso3": "MYS",
        "region": "Asia",
        "lat": 4.2105,
        "lon": 101.9758,
        "timezone": "Asia/Kuala_Lumpur",
        "locations": [("Kuala Lumpur", 3.1390, 101.6869, "Asia/Kuala_Lumpur")],
        "index": {"name": "FTSE Bursa Malaysia KLCI", "symbol": "^KLSE"},
    },
    {
        "country": "Philippines",
        "iso3": "PHL",
        "region": "Asia",
        "lat": 12.8797,
        "lon": 121.7740,
        "timezone": "Asia/Manila",
        "locations": [("Manila", 14.5995, 120.9842, "Asia/Manila")],
        "index": {"name": "PSEi", "symbol": "PSEI.PS"},
    },
    {
        "country": "Vietnam",
        "iso3": "VNM",
        "region": "Asia",
        "lat": 14.0583,
        "lon": 108.2772,
        "timezone": "Asia/Ho_Chi_Minh",
        "locations": [("Ho Chi Minh City", 10.8231, 106.6297, "Asia/Ho_Chi_Minh")],
        "index": {"name": "VN Index", "symbol": "^VNINDEX"},
    },
    {
        "country": "Australia",
        "iso3": "AUS",
        "region": "Oceania",
        "lat": -25.2744,
        "lon": 133.7751,
        "timezone": "Australia/Sydney",
        "locations": [
            ("Sydney", -33.8688, 151.2093, "Australia/Sydney"),
            ("Perth", -31.9523, 115.8613, "Australia/Perth"),
            ("Brisbane", -27.4698, 153.0251, "Australia/Brisbane"),
        ],
        "index": {"name": "S&P/ASX 200", "symbol": "^AXJO"},
    },
    {
        "country": "New Zealand",
        "iso3": "NZL",
        "region": "Oceania",
        "lat": -40.9006,
        "lon": 174.8860,
        "timezone": "Pacific/Auckland",
        "locations": [("Auckland", -36.8509, 174.7645, "Pacific/Auckland")],
        "index": {"name": "NZX 50", "symbol": "^NZ50"},
    },
    {
        "country": "South Africa",
        "iso3": "ZAF",
        "region": "Africa",
        "lat": -30.5595,
        "lon": 22.9375,
        "timezone": "Africa/Johannesburg",
        "locations": [
            ("Johannesburg", -26.2041, 28.0473, "Africa/Johannesburg"),
            ("Cape Town", -33.9249, 18.4241, "Africa/Johannesburg"),
        ],
        "index": {"name": "FTSE/JSE Top 40", "symbol": "^J200.JO"},
    },
    {
        "country": "Egypt",
        "iso3": "EGY",
        "region": "Africa",
        "lat": 26.8206,
        "lon": 30.8025,
        "timezone": "Africa/Cairo",
        "locations": [("Cairo", 30.0444, 31.2357, "Africa/Cairo")],
        "index": {"name": "EGX 30", "symbol": "CASE30.CA"},
    },
    {
        "country": "Saudi Arabia",
        "iso3": "SAU",
        "region": "Middle East",
        "lat": 23.8859,
        "lon": 45.0792,
        "timezone": "Asia/Riyadh",
        "locations": [("Riyadh", 24.7136, 46.6753, "Asia/Riyadh")],
        "index": {"name": "Tadawul All Share", "symbol": "^TASI.SR"},
    },
    {
        "country": "United Arab Emirates",
        "iso3": "ARE",
        "region": "Middle East",
        "lat": 23.4241,
        "lon": 53.8478,
        "timezone": "Asia/Dubai",
        "locations": [("Dubai", 25.2048, 55.2708, "Asia/Dubai")],
        "index": {"name": "Dubai Financial Market", "symbol": "DFMGI.AE"},
    },
]


G7_MARKET_CARDS: List[Dict[str, str]] = [
    {
        "title": "United States",
        "iso3": "USA",
        "index_name": "S&P 500",
        "symbol": "^GSPC",
    },
    {
        "title": "United Kingdom",
        "iso3": "GBR",
        "index_name": "FTSE 100",
        "symbol": "^FTSE",
    },
    {
        "title": "European Union",
        "iso3": "EUU",
        "index_name": "EURO STOXX 50",
        "symbol": "^STOXX50E",
    },
    {
        "title": "Japan",
        "iso3": "JPN",
        "index_name": "Nikkei 225",
        "symbol": "^N225",
    },
]


WEATHER_CODE_LABELS = {
    0: "Clear",
    1: "Mostly clear",
    2: "Partly cloudy",
    3: "Cloudy",
    45: "Fog",
    48: "Depositing fog",
    51: "Light drizzle",
    53: "Drizzle",
    55: "Heavy drizzle",
    56: "Freezing drizzle",
    57: "Heavy freezing drizzle",
    61: "Light rain",
    63: "Rain",
    65: "Heavy rain",
    66: "Freezing rain",
    67: "Heavy freezing rain",
    71: "Light snow",
    73: "Snow",
    75: "Heavy snow",
    77: "Snow grains",
    80: "Light showers",
    81: "Showers",
    82: "Heavy showers",
    85: "Light snow showers",
    86: "Heavy snow showers",
    95: "Thunderstorm",
    96: "Thunderstorm with hail",
    99: "Severe thunderstorm",
}
